# Generated by Django 2.2.3 on 2019-08-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=75)),
                ('date_encoded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
