# Generated by Django 2.2.3 on 2019-08-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='on process', max_length=75),
        ),
    ]
