# Generated by Django 2.2.3 on 2019-08-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='small', max_length=20),
        ),
    ]
