# Generated by Django 2.2.3 on 2019-08-29 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_encoded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
