# Generated by Django 2.2.3 on 2019-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20190831_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_status',
            field=models.IntegerField(default=0),
        ),
    ]
