# Generated by Django 2.2.3 on 2019-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20190831_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ship_status',
            new_name='shipping_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.BooleanField(default=True),
        ),
    ]
