# Generated by Django 2.2.3 on 2019-08-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20190831_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.BooleanField(default=False),
        ),
    ]
