# Generated by Django 2.2.3 on 2019-09-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20190901_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
