# Generated by Django 2.2.3 on 2019-09-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordersummary',
            name='total_qty',
        ),
    ]
