# Generated by Django 2.2.3 on 2019-09-11 13:59

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20190911_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bulk_price',
            field=computed_property.fields.ComputedDecimalField(compute_from='price', decimal_places=2, default=0, editable=False, max_digits=7),
            preserve_default=False,
        ),
    ]
