# Generated by Django 2.2.3 on 2019-09-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_orderitem_bulk_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='bulk_price',
        ),
    ]
