# Generated by Django 2.2.3 on 2019-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20190912_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
